#include "lib.h"

void umain()
{
	if(fork()==0)
		if(fork()==0)
			if(fork()==0)
				if(fork()==0)
					if(fork()==0)
						if(fork()==0)
							if(fork()==0)
								if(fork()==0)
									if(fork()==0)
										if(fork()==0)
											if(fork()==0)
												if(fork()==0)
													if(fork()==0)
														if(fork()==0)
															if(fork()==0)
																if(fork()==0)
																	if(fork()==0)
																		if(fork()==0)
																			if(fork()==0)
																				if(fork()==0)
																					if(fork()==0)
																						if(fork()==0)
																							if(fork()==0)
																								if(fork()==0)
																									if(fork()==0)
																										if(fork()==0)
																											if(fork()==0)
																												if(fork()==0)
																													if(fork()==0)
																														if(fork()==0)
																														{}
}
